- name:  Update and reboot server
  hosts: "{{ hosts }}"

  tasks:
    - name: Update repositories cache
      apt:
        update_cache: yes

    - name: Upgrade all packages to their latest version
      apt:
        upgrade: 'full'

    - name: Clean the local repository and remove unused dependency packages
      apt:
        autoclean: yes
        autoremove: yes

    - name: Reboot hosts
      reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
